baseurl: ''
permalink: pretty
title: Video Studio
google_analytics_id: ''
homepage:
  show_call_box: true
logo:
  mobile: images/logo/logoA00.png
  desktop: images/logo/logoA00.png
  desktop_height: 44px
seo:
  meta_og_title: Video Production Studio
  meta_og_type: website
  meta_og_url: 'https://neat-cabbage-64f52.netlify.app/'
  meta_og_image: >-
    https://raw.githubusercontent.com/almakon/neat-cabbage-64f52/master/screenshots/tn.png
  meta_og_description: >-
    Corporate Video Production
collections:
  services:
    output: true
  team:
    output: true
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-environment-variables
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
url: ''
